volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py load_ingridients data/ingredients.json && python manage.py load_tags data/tags.json && gunicorn --bind 0.0.0.0:8000 backend.wsgi"
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    build: ./nginx/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/mediafiles
    ports:
      - 8000:80
    depends_on:
      - backend