# Generated by Django 4.2.16 on 2025-01-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(choices=[('завтрак', 'breakfast'), ('обед', 'lunch'), ('ужин', 'dinner')], max_length=32, unique=True, verbose_name='Уникальный слаг'),
        ),
    ]
